### ISSUE TITLE
[bug] CARGO_HOME is not considered when trying to copy cargo-appimage-runner

### ISSUE THREAD

**Issue by dzervas** [StratusFearMe21/cargo-appimage#15]
I've stumbled upon a weird case where `CARGO_HOME` is not `~/.cargo`. I'm trying to build my app inside a docker container (`rust:slim`) and:

```bash
root@60a8693b1786:/src/app# echo $CARGO_HOME
/usr/local/cargo
root@60a8693b1786:/src/app# ls /usr/local/cargo/bin/
cargo  cargo-appimage  cargo-appimage-runner  cargo-clippy  cargo-fmt  cargo-miri  clippy-driver  rls  rust-gdb  rust-lldb  rustc  rustdoc  rustfmt  rustup
```

https://github.com/StratusFearMe21/cargo-appimage/blob/4cdf65fae7289d733bcf2e3830da277b6f49caf5/src/main.rs#L243

I'm not sure if `CARGO_HOME` is always populated (if it's not cargo sets it during build maybe?) so you might need to use env and fall back to `$HOME/.cargo`.

**Comment by StratusFearMe21** [comment]
Thanks for opening these issues, never would've found these edge cases without them
