### ISSUE TITLE
No such file or directory (APPDIR/usr/bin/bin)

### ISSUE THREAD

**Issue by zinifier** [StratusFearMe21/cargo-appimage#22]
Hello, trying to run AppImage i get a "no such file or directory".

That's because the apprun helper tries to run APPDIR/usr/bin/bin which does not exist since now (after #21) each binary target for the crate gets copied to its own name (eg `mybin` to `APPDIR/usr/bin/mybin`) but apprun has no idea about this.

My quickest hack to get it working is to find the .desktop file at the root of the AppDir and find corresponding name in the bin directory. I can make a PR but maybe you have a better idea how to fix it?

**Comment by StratusFearMe21** [comment]
oops, I've reverted the changes to `src/apprun.rs` for now

**Comment by StratusFearMe21** [comment]
This should be fixed as well
