### ISSUE TITLE
PATH in AppDir

### ISSUE THREAD

**Issue by zinifier** [StratusFearMe21/cargo-appimage#23]
The apprun helper does not change PATH so if i have a binary assets in `AppDir/bin` or `AppDir/usr/bin` i can't call it from within the appimage.

Could we maybe add a setting like `allow_outside_path`? When enabled, `AppDir/usr/bin` is prepended to `PATH`. When disabled, `PATH` only contains `AppDir/usr/bin` and cannot call system tools.

I'm happy to make a PR if that sounds good to you.

**Comment by StratusFearMe21** [comment]
Okay, this issue should be fixed with the issue mentioned, thanks for bringing it to my attention
