### ISSUE TITLE
Support version.workspace = true

### ISSUE THREAD

**Issue by HKalbasi** [StratusFearMe21/cargo-appimage#29]
I'm trying to build an appimage for [c2rust](https://github.com/immunant/c2rust). When I run `cargo appimage` in the root of this project, I get:
```
/workspace/c2rust (master) $ cargo appimage
    Finished release [optimized] target(s) in 0.45s
Error: Cannot load metadata from Cargo.toml
```
When I try running it inside the `c2rust` directory:
```
/workspace/c2rust/c2rust (master) $ cargo appimage
    Finished release [optimized] target(s) in 0.07s
Error: Cannot find Cargo.toml

Caused by:
    0: invalid type: map, expected a string for key `package.version` at line 3 column 21
    1: invalid type: map, expected a string for key `package.version` at line 3 column 21
```
Should I do something special for using this tool from workspaces, or it's just not supported yet?

**Comment by StratusFearMe21** [comment]
The latest release (2.2.0) should fix this issue. Thanks for bringing this to my attention ☺

**Comment by HKalbasi** [comment]
Thanks for the quick fix! I'm now getting this error:
```
Error: Could not fill in the gaps in Cargo.toml
```
What is the problem here? What I should add to the `Cargo.toml` file?

Closing the issue as the original problem is resolved.

**Comment by StratusFearMe21** [comment]
@HKalbasi I was able to solve this by cd'ing into the `c2rust` directory within the `c2rust` project
```
git clone https://github.com/immunant/c2rust
cd c2rust/c2rust
cargo appimage
```
I hope this helps

**Comment by StratusFearMe21** [comment]
Oops, nvm, I'm working on it

**Comment by StratusFearMe21** [comment]
I can reproduce it, but I have no clue why it's doing this. The error says `No such file or directory (os error 2)`, but not even `strace` will show me which file produced that error. This is very confusing
