### ISSUE TITLE
[Feature Request]: Release/Debug

### ISSUE THREAD

**Issue by lexi-the-cute** [StratusFearMe21/cargo-appimage#30]
`--release` should be specified by the user so it doesn't assume release if the user expects it to be building debug when not specified

**Comment by StratusFearMe21** [comment]
Well, if you're building an AppImage, chances are it's for distributing to users (and thus merits release). But if you need to make a debug AppImage, you can pass `--profile=dev` to the program

**Comment by lexi-the-cute** [comment]
Thanks!
