### ISSUE TITLE
Doesn't work for crates with multiple binaries, or crates where the binary has a different name from the crate.

### ISSUE THREAD

**Issue by cessen** [StratusFearMe21/cargo-appimage#5]
First of all: thank you for this amazing project!  This really takes the pain out of building appimages from Rust projects.  Now to the issue...

I'm currently working on a project that builds multiple executable binaries (they share dependencies and a lot of backend code, and are intended to be a suite of tools).  Ideally I would like all of them to be built into separate appimages.

However, right now cargo-appimage appears to only look for a single executable with the same name as crate:
https://github.com/StratusFearMe21/cargo-appimage/blob/61fdd8e0a9bba0353fbaa720cbed45095edf013c/src/main.rs#L158-L162

This means that in my project it simply fails with "Cannot find binary file".

**Comment by StratusFearMe21** [comment]
I got you, that was an oversight on my part. Gimme a minute to implement this.

**Comment by StratusFearMe21** [comment]
Okay, I've implemented this feature in the latest version (1.3.0). Apps with multiple binaries defined will built as such

**Comment by cessen** [comment]
Oh wow!  That was fast!  Thanks so much!  I'll test it out the next chance I get and report back.

**Comment by cessen** [comment]
Just tested, and as far as I can tell it works like a charm.  Thanks!
